# Generated by Django 4.1 on 2023-10-06 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='gpslatlon',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
